scrooge_scala_library(
    name = "shop",
    visibility = ["//visibility:public"],
    deps = [
        ":thrift",
    ],
)

thrift_library(
    name = "thrift",
    srcs = glob(["*.thrift"]),
    visibility = ["//visibility:public"],
)
